#!/usr/bin/env bash
#
# Run cmd/cigocacher based on the revision pinned in tool/cigocacher.rev
# Note, unlike our other tools, this one never sets -x because it may
# print sensitive auth tokens. These should be masked by GitHub, but better
# to be safe.

set -euo pipefail

goos() {
    case "$(uname -s)" in
        Linux*)
            echo "linux"
            ;;
        Darwin*)
            echo "darwin"
            ;;
        MINGW*|MSYS*|CYGWIN*)
            echo "windows"
            ;;
        *)
            echo "unknown"
            ;;
    esac
}

goarch() {
    local machine="$(uname -m)"
    case "$machine" in
        x86_64|amd64)
            echo "amd64"
            ;;
        aarch64|arm64)
            echo "arm64"
            ;;
        armv7l|armv6l)
            echo "arm"
            ;;
        i386|i686)
            echo "386"
            ;;
        *)
            echo "$machine"
            ;;
    esac
}

cachedir="${HOME}/.cache/tailscale-cigocacher"

(
    SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
    repo_root="${SCRIPT_DIR}/../"
    cd "$repo_root"

    tarball="${cachedir}.tar.gz"

    want_rev="$(cat ./tool/cigocacher.rev)"
    got_rev=""
    if [[ -x "${cachedir}/cigocacher" ]]; then
        got_rev=$("${cachedir}/cigocacher" --version | tr -d '\r\n')
    fi

    if [[ "$want_rev" != "$got_rev" ]]; then
        echo "Downloading cigocacher rev ${want_rev} (got ${got_rev})" >&2
        rm -rf "$cachedir" "$tarball"
        mkdir -p "$cachedir"
        curl -fsSL -o "$tarball" "https://github.com/tailscale/tailscale/releases/download/cmd%2Fcigocacher%2F${want_rev}/cigocacher-$(goos)-$(goarch).tar.gz"
        (cd "$cachedir" && tar -xf "$tarball")
        rm -f "$tarball"
    fi
)

exec "${cachedir}/cigocacher" "$@"
